apiVersion: v1
kind: Service
metadata:
  name: cpu-service
spec:
  selector:
    app: cpu-app #any pod with started with this lables
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
  type: LoadBalancer